platform :ios, '13.0'

target 'Flash Chat iOS13' do
  use_frameworks!
  
  pod 'CLTypingLabel', '~> 0.4.0'
  
  # Pods for Flash Chat iOS13
  
  pod 'Firebase/Auth', :inhibit_warnings => true
  pod 'Firebase/Firestore', :inhibit_warnings => true

end
